
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: npm run build
      - run: zip -r dist.zip dist/

      # save artifacts
      - persist_to_workspace:
          root: ./
          paths: 
            - dist.zip

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  sonar:
    docker:
      - image: circleci-sonar-scanner-docker
    steps:
      - checkout
      - run: sonar-scanner -Dsonar.projectKey=Soontao_PDISolutionCenterFront -Dsonar.organization=soontao-github -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=5d7391c85b44731ca7c69028195ed84c3dcfee54

  deploy:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/artifacts/dist.zip

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - sonar:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
